### ISSUE TITLE
Manage an ASG scale up / down schedule

### ISSUE THREAD

**Issue by mostlygeek** [mozilla-services/reaper#19]
Most of our instance hours are burned in ASG used for stage that are left up to be available when we need them. We can save a lot of money if we scale ASGs down to zero and back up to `desiredInstances`. 

Some ideas for how this would work: 
- if a new unmanaged (no reaper state tag) ASG is discovered, email the owner if they want to set a schedule
- schedule options should respect timezones
- schedule should be centered around normal business hours, 8am to 6pm Monday to Friday
- outside of the ON schedule, reaper should scale instances down to zero
- the schedule should match what user's actually require for the service to be up. People shouldn't have to work around saving a few dollars 

It would be a good idea to talk to the QA team as stage has the most instances spun up via ASGs and they are the primary users.

**Comment by milescrabill** [comment]
Closing as fixed as of https://github.com/mozilla-services/reaper/pull/51. https://github.com/mozilla-services/reaper/pull/54 adds an interface for adding schedules from events.

In response to your ideas:
The REAPER_AUTOSCALER tag is separate from the REAPER tag. Newly discovered reapable resources have events that are triggered (on their First state). If so configured, this will fire a Datadog / Email event that includes links to set scaling schedules for the resource for Pacific, Eastern, and CEST business hours.
All scheduling is done using UTC.
The default schedules are around the business hours for each time zone.
AutoScalingGroups are scaled to 0 when scaled down. Instances are stopped.
Each schedule consists of a scale down and scale up portion. Schedules are in cron syntax, so they are quite flexible per users' needs.

From Mana:
Tagging an Instance or AutoScalingGroup with a tag key "REAPER_AUTOSCALER" and a value following the below causes it to scheduled for scaling by Reaper.
- If tagging an Instance, the tag consists of two sections separated by a comma.
  - Note: an Instance that is scheduled will be stopped/started on scale down/up.
  - Both sections are in Cron syntax. First is the scale down schedule, second is the scale up schedule. Note: Reaper uses UTC.
    - Ex: "0 30 1 \* \* 2-6,0 30 14 \* \* 1-5".
    - The above tag reads: at 1:30 UTC, Tuesday through Saturday, stop this instance. At 14:30, Monday through Friday, start this instance. These times convert to scaling down at 6:30PM Pacific and scaling up at 7:30AM Pacific, a rough approximation of Pacific business hours.
  - I advise using a tool like Crontab Generator if you aren't a cron wizard.
- If tagging an AutoScalingGroup, the tag has four comma separated sections (scale down schedule, scale up schedule, desired size, min size).
  - Note: an AutoScalingGroup that is scheduled will have its desired and minimum sizes set to 0/set back to their previous values on scale down/up.
  - The first two sections are the scale down and scale up schedules, the same as for instances. The third and fourth sections are simply integers, the desired size and minimum size the ASG should be returned to when scaled up.
    - Ex: "0 30 1 \* \* 2-6,0 30 14 \* \* 1-5,2,1"
    - The above tag reads: 1:30 UTC, Tuesday through Saturday, scale this AutoScalingGroup down to minimum size 0 and desired size 0. At 14:30, Monday through Friday, scale this AutoScalingGroup up to desired size 2 and minimum size 1. These times convert to scaling down at 6:30PM Pacific and scaling up at 7:30AM Pacific, a rough approximation of Pacific business hours.
