### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by whd** [mozilla-services/reaper#31]
For users of the reaper, there should be a description of program configuration and operation. Particularly, the various reapable resource types and the filters available on those resources should be available without having to read the code, whether this be by a command line listing or by documentation files. A section on the interactive mode could be potentially useful as well.

For users affected by the forthcoming Mozilla installation there should be documentation on what to expect, which is probably better suited for mana or an internal wiki.

For developers there should be some decent code documentation (which possibly already exists) .

**Comment by milescrabill** [comment]
There is now a Mana page, as well as improved documentation per https://github.com/mozilla-services/reaper/pull/45
